name: Release
on:
  push:
    branches:
    - main
    - next

jobs:
  semantic-release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Install GitHub App Token
      uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ secrets.APP_ID }}
        private-key: ${{ secrets.PRIVATE_KEY }}
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ steps.app-token.outputs.token }}
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      with:
        semantic_version: 23.0.2
        extra_plugins: |
          conventional-changelog-conventionalcommits@7.0.2
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
