name: Release
on:
  push:
    branches:
    - main
    - next

jobs:
  semantic-release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      with:
        semantic_version: 23.0.2
        extra_plugins: |
          conventional-changelog-conventionalcommits@7.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
