name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create and push semver tag
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
            
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          name: ${{ steps.semver.outputs.next }}
          token: ${{ github.token }}
