name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Install GitHub App Token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIV_KEY }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run tests
        run: |
          go mod tidy
          go test -v ./...
      - name: Create and push semver tag
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          noNewCommitBehavior: warn
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          name: ${{ steps.semver.outputs.next }}
          token: ${{ steps.app-token.outputs.token }}
